# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 15:26
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tstart', models.DateTimeField()),
                ('tend', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthnet.Address')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('level', models.IntegerField(choices=[(0, 'Error'), (1, 'Info'), (2, 'Warning')], default=0)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('refills', models.IntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthnet.Address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthnet.User')),
            ],
            options={
                'abstract': False,
            },
            bases=('healthnet.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthnet.User')),
                ('hospitals', models.ManyToManyField(blank=True, to='healthnet.Hospital')),
            ],
            options={
                'abstract': False,
            },
            bases=('healthnet.user',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthnet.User')),
                ('doctors', models.ManyToManyField(to='healthnet.Doctor')),
            ],
            options={
                'abstract': False,
            },
            bases=('healthnet.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthnet.User')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Unspecified'), (2, 'Male')], default=2, null=True)),
                ('marital_status', models.IntegerField(blank=True, choices=[(0, 'Divorced'), (1, 'Separated'), (2, 'Widowed'), (3, 'Married'), (4, 'LivingCommonLaw'), (5, 'Single'), (6, 'Unspecified')], default=6, null=True)),
                ('health_insurance_provider', models.CharField(blank=True, max_length=15, null=True)),
                ('health_insurance_number', models.CharField(max_length=10, unique=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Address')),
                ('doctors', models.ManyToManyField(blank=True, to='healthnet.Doctor')),
            ],
            options={
                'abstract': False,
            },
            bases=('healthnet.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='appointments',
            field=models.ManyToManyField(blank=True, to='healthnet.Appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendees',
            field=models.ManyToManyField(to='healthnet.User'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthnet.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthnet.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='healthnet.Prescription'),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_care_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_care_provider', to='healthnet.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='records',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.MedicalRecord'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nurses',
            field=models.ManyToManyField(blank=True, to='healthnet.Nurse'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, to='healthnet.Patient'),
        ),
    ]
