# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Warning'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'LivingCommonLaw'), (2, 'Widowed'), (3, 'Separated'), (4, 'Single'), (5, 'Married'), (6, 'Divorced')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
