# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0002_auto_20160405_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Divorced'), (1, 'LivingCommonLaw'), (2, 'Widowed'), (3, 'Single'), (4, 'Unspecified'), (5, 'Separated'), (6, 'Married')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Unspecified'), (2, 'Male')], default=2, null=True),
        ),
    ]
