# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0003_auto_20160410_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='hospital',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(default='', to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Info'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Separated'), (1, 'Single'), (2, 'Unspecified'), (3, 'Married'), (4, 'Widowed'), (5, 'Divorced'), (6, 'LivingCommonLaw')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
