# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0005_auto_20160410_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(null=True, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Error'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Divorced'), (1, 'Married'), (2, 'Unspecified'), (3, 'LivingCommonLaw'), (4, 'Separated'), (5, 'Widowed'), (6, 'Single')], default=6, null=True),
        ),
    ]
