# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0006_auto_20160410_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, null=True, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Info'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'LivingCommonLaw'), (1, 'Widowed'), (2, 'Married'), (3, 'Separated'), (4, 'Single'), (5, 'Divorced'), (6, 'Unspecified')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Male'), (2, 'Female')], default=2, null=True),
        ),
    ]
