# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0007_auto_20160410_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Error'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Widowed'), (1, 'Married'), (2, 'Single'), (3, 'Unspecified'), (4, 'LivingCommonLaw'), (5, 'Separated'), (6, 'Divorced')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Unspecified'), (2, 'Female')], default=2, null=True),
        ),
    ]
