# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0008_auto_20160410_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Warning'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'LivingCommonLaw'), (2, 'Widowed'), (3, 'Separated'), (4, 'Single'), (5, 'Divorced'), (6, 'Married')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Male'), (2, 'Female')], default=2, null=True),
        ),
    ]
