# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0010_auto_20160410_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Error'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'LivingCommonLaw'), (1, 'Divorced'), (2, 'Married'), (3, 'Single'), (4, 'Widowed'), (5, 'Separated'), (6, 'Unspecified')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
