# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0011_auto_20160410_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Divorced'), (1, 'Separated'), (2, 'LivingCommonLaw'), (3, 'Single'), (4, 'Married'), (5, 'Widowed'), (6, 'Unspecified')], default=6, null=True),
        ),
    ]
