# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0013_auto_20160410_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Separated'), (2, 'Unspecified'), (3, 'Widowed'), (4, 'LivingCommonLaw'), (5, 'Divorced'), (6, 'Single')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
