# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0014_auto_20160410_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Warning'), (2, 'Info')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Widowed'), (1, 'LivingCommonLaw'), (2, 'Married'), (3, 'Unspecified'), (4, 'Separated'), (5, 'Single'), (6, 'Divorced')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
