# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0018_auto_20160410_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Info'), (2, 'Warning')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Widowed'), (1, 'Divorced'), (2, 'Separated'), (3, 'Married'), (4, 'Unspecified'), (5, 'LivingCommonLaw'), (6, 'Single')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Male'), (2, 'Female')], default=2, null=True),
        ),
    ]
