# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0019_auto_20160410_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Doctor'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Nurse'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Patient'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Warning'), (1, 'Info'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Married'), (2, 'Separated'), (3, 'Unspecified'), (4, 'LivingCommonLaw'), (5, 'Divorced'), (6, 'Widowed')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Unspecified')], default=2, null=True),
        ),
    ]
