# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0020_auto_20160410_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='nurses',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, null=True, to='healthnet.Hospital'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Error'), (2, 'Warning')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Widowed'), (2, 'LivingCommonLaw'), (3, 'Divorced'), (4, 'Unspecified'), (5, 'Separated'), (6, 'Single')], default=6, null=True),
        ),
    ]
