# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0021_auto_20160410_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthnet.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Separated'), (1, 'Married'), (2, 'LivingCommonLaw'), (3, 'Widowed'), (4, 'Unspecified'), (5, 'Divorced'), (6, 'Single')], default=6, null=True),
        ),
    ]
