# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0022_auto_20160410_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Married'), (2, 'Widowed'), (3, 'LivingCommonLaw'), (4, 'Separated'), (5, 'Divorced'), (6, 'Single')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Unspecified'), (2, 'Male')], default=2, null=True),
        ),
    ]
