# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0023_auto_20160410_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Info'), (2, 'Warning')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'LivingCommonLaw'), (2, 'Separated'), (3, 'Married'), (4, 'Widowed'), (5, 'Unspecified'), (6, 'Divorced')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Unspecified'), (2, 'Female')], default=2, null=True),
        ),
    ]
